name: Build on Arch Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Update system and install dependencies
      run: |
        pacman -Syu --noconfirm
        # We'll install these after caching, if they aren't already present from a cached pacman state
        pacman -S --noconfirm base-devel rust pkg-config git

    - name: Cache Pacman packages
      uses: actions/cache@v4
      with:
        path: /var/cache/pacman/pkg
        key: ${{ runner.os }}-pacman-${{ hashFiles('**/PKGBUILD', '**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-pacman-

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      run: |
        cargo build --verbose

    - name: Run tests
      run: |
        cargo test --verbose
